### ISSUE TITLE
Post page / Header

### ISSUE THREAD

**Issue by viniromualdo** [greenpeace/planet4-master-theme#145]
In [post pages](https://dev.p4.greenpeace.org/international/issues/forest/10494/test-image/), on link (in hot pink) above the top title, substitute "content type" info (POST • ...) by "article type" info (i.e.: STORY • ...)

It should still be linked and clicking on it take the users to a refined search result page with the "article type" filter applied to it.

Remember there's only 3 article types: Press release, Story and Publication.
Here's a mocked up example:
![post_header](https://user-images.githubusercontent.com/12191933/34195537-5b8a4c3c-e55e-11e7-9e51-914c15df9da8.png)

**Comment by sagarsdeshmukh** [comment]
Resolve the issue
