### ISSUE TITLE
Twig / Timber output escaping strategy

### ISSUE THREAD

**Issue by johnbillion** [greenpeace/planet4-master-theme#3]
Having good control over the output format of fields on the site is important for security concerns. This is why the WordPress VIP coding standards require that every variable echoed out is wrapped in either an escaping function such as `esc_html()` or a filtering function such as `wp_kses_post()` (ref: https://vip.wordpress.com/documentation/code-review-what-we-look-for/#validation-sanitization-and-escaping).

With Twig and Timber in use, this strategy changes slightly. The intention of Twig templating is to provide a clear, concise templating language that non-technical users can understand. If every field was required to be wrapped in a call to `esc_html()`, via `{{ field|e('esc_html') }}`, several of the benefits of Twig are negated.

To that end, I recommend that the P4 theme enables Twig's automatic escaping option, and then opts to use the raw or filtered output for fields which require HTML. This means you can ensure that every field is escaped unless explicitly stated otherwise.

Implementation:

* `Timber::$autoescape = true;` should be added to the top of `functions.php` near where [the other `Timber` class properties are set](https://github.com/greenpeace/planet4-master-theme/blob/5bf0c08fe9b3a81e4a6274cd71d84e171bd4a19c/functions.php#L15). This enables automatic escaping of all fields that are output using `{{` double braces `}}` and provides significant security hardening.
* Fields which need to output raw HTML should be piped through `raw`. Example for the post body content:
    `{{ {{post.post_conten|raw}}`
* Fields which need to output potentially untrusted HTML should be piped through a filtering function as well as `raw`. Example for a post meta field value:
    `{{ post.custom_field_key|e('wp_kses_post')|raw }}`
* Fields which need all HTML stripped should be piped through one of Twig's built-in filters. Example for a post meta field value:
    `{{ post.custom_field_key|striptags }}`

This strategy encourages developers of the theme to use fewer fields which allow HTML, which improves the user experience for editors, while at the same time allowing such fields to be implemented in a secure manner.

**Comment by 27Bslash6** [comment]
Agreed, autoescape by default

**Comment by johnbillion** [comment]
It looks like I can't assign issues here, so pinging @sagarsdeshmukh, @angtheod, and @mcshanea for review.

**Comment by koyan** [comment]
Decision taken. We are going for autoescape by default. I have added the 
Timber::$autoescape = true;
@sagarsdeshmukh @kirdia @angtheod @27Bslash6 FYI. Implementing this may break things you have already made. Unfortunately our automated testing is not yet in place. Please retest what you have implemented already via timber, and pay special attention to any raw output you have.

**Comment by koyan** [comment]
@johnbillion , after enabling Timber::$autoescape = true;  
all output (including the normal html that is inside the twig templates) is escaped and presented as html entities. We have not managed to find what causes that. Have you implemented this in the past?

**Comment by angtheod** [comment]
Instead of using Timber's autoescape which looks like it escapes all html tags, we can wrap our twig templates inside
{% autoescape 'html' %}
....
{% endautoescape %}

and for output that we has html that we want to allow we can use the |raw filter.

Same for js code we can wrap it inside
{% autoescape 'js' %}
....
{% endautoescape %}

**Comment by johnbillion** [comment]
I've so far been unable to reproduce this issue. The HTML contained within the Twig templates themselves should not be getting escaped as they fall outside of the domain of Twig.

On my local installation the `Timber::$autoescape = true;` appears to be working as intended.

Can you let me know the exact version of Twig and Timber that's in use on the affected site please?

**Comment by johnbillion** [comment]
I've just noticed that `{{post.content}}` in the templates needs to be replaced with `{{post.content|raw}}`, otherwise the HTML in the post content will be escaped. Is this what you're referring to?

**Comment by angtheod** [comment]
Yes @johnbillion you are right, it needed the raw filter there.
Now it works, as expected.

**Comment by angtheod** [comment]
Included this in last PR from timber-autoescape into develop. I believe it can be closed @koyan .
