### ISSUE TITLE
Evaluate upgrading composer Timber library require to 1.5.*

### ISSUE THREAD

**Issue by 27Bslash6** [greenpeace/planet4-master-theme#4]
The Timber library on packagist is currently at 1.5.x and documents several performance improvements and a few bugfixes that may warrant investigation:

https://github.com/timber/timber/releases

**Comment by angtheod** [comment]
It's not yet in wpackagist :(
https://wpackagist.org/search?q=timber-library&type=any&search=

**Comment by angtheod** [comment]
So, today Timber 1.5.0 is available from wpackagist.org.
I'm going to test it locally and see if any problems occur.

**Comment by angtheod** [comment]
@koyan @mcshanea Should I go ahead and update? I have it for a few days locally, no problems so far.

**Comment by koyan** [comment]
@angtheod Yes, please go on and update it.
