### ISSUE TITLE
Notice error on k8s/base - Only variables should be passed by reference in class-p4-post.php

### ISSUE THREAD

**Issue by 27Bslash6** [greenpeace/planet4-master-theme#551]
https://k8s.p4.greenpeace.org/base/

`Notice: Only variables should be passed by reference in /app/source/public/wp-content/themes/planet4-master-theme/classes/class-p4-post.php on line 116`

https://github.com/greenpeace/planet4-master-theme/blob/d15e7be8f80730a223b27a5c395eb42e849a31ac/classes/class-p4-post.php#L112-L121

**Comment by koyan** [comment]
Created in Jira as: https://jira.greenpeace.org/browse/PLANET-2581
